encoding: unicode
pool: 5
timeout: 5000
adapter: postgresql
database: munin
username: postgres
password: password
encoding: unicode

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: munin
  username: postgres
  password: password
  encoding: unicode

test:
  <<: *default
  database: munin
  username: postgres
  password: password
  encoding: unicode

production:
  <<: *default
  database: munin
  username: postgres
  password: password
  encoding: unicode
